### ISSUE TITLE
No devices for CPU-only run

### ISSUE THREAD

**Issue by roclark** [HewlettPackard/dlcookbook-dlbs#1]
I am having some issues with a CPU-only run of the benchmark suite on one of my GPU-less nodes. I am trying to use the Tensorflow framework for my test, but I get an error in the log (see below). Looking at the code it appears (from my angle at least) that `tf_cnn_benchmarks.py` is looking for GPU devices, which I have none, causing `self.devices` to be zero, hence the divide by zero error. Perhaps I am off-base though?

I looked at several of the CPU-only commands in the Wiki guide, but none of them have been successful - most still require a GPU it appears in my testing.

Environment: `CentOS 7.4 64-bit`
Docker Build: `hpe/tensorflow:cpu`
Framework: `Tensorflow`
Command:
```
python python/dlbs/experimenter.py run -Pexp.framework='"tensorflow"' -Pexp.env='"docker"' -Pexp.phase='"training"' -Pexp.gpus='""' -Pexp.model='"alexnet"' -Pexp.device_batch='"16"' -Pexp.log_file='"./benchmarks/my_experiment/tf.log"' -Ptensorflow.docker.image='"hpe/tensorflow:cpu"' -Pexp.device='"cpu"'
```

```bash
----------------------------
Starting framework launcher.
----------------------------
01-04-18 17:55:58 [INFO]    /root/dlbs/scripts/launchers/tensorflow_hpm.sh
__exp.framework_title__= "TensorFlow"
__tensorflow.version__= "1.0.1"
__results.start_time__= "2018-01-04:23:56:01:230"
PYTHONPATH=/workspace/tf_cnn_benchmarks:/workspace/tf_cnn_benchmarks: CUDA_VISIBLE_DEVICES=
BenchmarkCNN::__init__ time=0.056028 ms
TensorFlow:  1.0
Model:       alexnet
Mode:        training
Batch size:  0 global
Traceback (most recent call last):
  File "/workspace/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 1454, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/workspace/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 1449, in main
    bench.print_info()
  File "/workspace/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 970, in print_info
    log_fn('             %s per device' % (self.batch_size / len(self.devices)))
ZeroDivisionError: integer division or modulo by zero
__results.end_time__= "2018-01-04:23:56:02:826"
__results.proc_pid__= 44072
```

Thanks for putting this together by the way! I'm really excited to take a deeper dive into it once I get this issue resolved. Let me know if you need any additional information.

**Comment by sergey-serebryakov** [comment]
Hi @roclark,
Thanks for this info. I just committed a patch that should fix it. I have updated CPU TensorFlow dockerfile, I suggest you should build it and use it (1.4) instead of your current version (1.0):

```bash
docker rmi hpe/tensorflow:cpu  # You may need to delete containers if this fails

cd ./dlcookbook/docker
./build.sh tensorflow/cpu

cd ..
rm -rf ./benchmarks/my_experiment
python python/dlbs/experimenter.py run -Pexp.framework='"tensorflow"' -Pexp.env='"docker"' -Pexp.phase='"training"' -Pexp.model='"alexnet"' -Pexp.device_batch='"16"' -Pexp.log_file='"./benchmarks/my_experiment/tf.log"' -Ptensorflow.docker.image='"hpe/tensorflow:cpu"' -Pexp.device='"cpu"'
```

You do not need to specify `-Pexp.gpus='""' ` if compute device is set to `cpu`.

**Comment by sergey-serebryakov** [comment]
Also please keep in mind that that docker file (`hpe:tensorflow/cpu`) is not specifically optimized for CPU. If you really want to run TF on CPUs and get good performance, just send me a quick note and I'll build it.

**Comment by roclark** [comment]
This is great! Thank you very much @sergey-serebryakov for the quick response and update! I am now able to run CPU-only benchmarks on my system. No worries on the non-optimal performance of the CPU config. I am only testing with this configuration to get a feel for the suite until I get my hands on a GPU, so I'm not looking too closely at the raw performance at the moment.
