### ISSUE TITLE
Support for new Docker runtime (Docker 19.03)

### ISSUE THREAD

**Issue by DerekChia** [HewlettPackard/dlcookbook-dlbs#16]
I went through https://hewlettpackard.github.io/dlcookbook-dlbs/#/runtimes/runtimes?id=runtimes and noticed that the new `docker run --gpus all` format for Docker 19.03 is not supported. 

Is there any plans to modify your code to support that? Thanks.

Reference:
https://github.com/NVIDIA/nvidia-docker

**Comment by joehandzik** [comment]
@DerekChia I would say long-term the answer is yes, but we'd probably need to support both the legacy and new methods. If, in the short-term, you're just looking to get something up and running, I was able to get something working on a single GPU system this morning with minimal edits (definitely wouldn't say they're ready for prime-time yet). Leaving a link here in case it helps you: https://github.com/joehandzik/dlcookbook-dlbs/tree/wip-new-docker

**Comment by DerekChia** [comment]
> @DerekChia I would say long-term the answer is yes, but we'd probably need to support both the legacy and new methods. If, in the short-term, you're just looking to get something up and running, I was able to get something working on a single GPU system this morning with minimal edits (definitely wouldn't say they're ready for prime-time yet). Leaving a link here in case it helps you: https://github.com/joehandzik/dlcookbook-dlbs/tree/wip-new-docker

Thank you for looking into this; i'll look into the branch.
