### ISSUE TITLE
Feature request: Add PyTorch support

### ISSUE THREAD

**Issue by joehandzik** [HewlettPackard/dlcookbook-dlbs#3]
Through some customer conversations, it's becoming apparent that we'll want PyTorch support sooner or later. How much of a lift would it be to add PyTorch support?

**Comment by sergey-serebryakov** [comment]
I've also got requests for pyTorch. It'll depend on if there's something in community we can reuse. I'll figure this out.

**Comment by sergey-serebryakov** [comment]
PyTorch was added and now is the part of the Deep Learning Benchmarking Suite.
