### ISSUE TITLE
InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'fp32_vars/dense/bias/Momentum'

### ISSUE THREAD

**Issue by bingws** [HewlettPackard/dlcookbook-dlbs#9]
@sergey-serebryakov   hi , I've successfully tried GPU benchmarking by using the TensorFlow image, so I wanted to try CPU benchmarking. Additionally, I have successfully tested caffe's CPU benchmark.
My command line：
`python ./python/dlbs/experimenter.py run  -Pexp.framework='"nvtfcnn"'  -Pexp.gpus='""' -Vexp.docker=true  -Pexp.log_file='"./benchmarks/my_experiment/tf_${exp.model}_${exp.replica_batch}.log"' -Vexp.model='["alexnet", "googlenet"]' -Vexp.replica_batch='[2, 4]'  -Ptensorflow.docker_image='"tensorflow/tensorflow:latest"' -Pexp.docker_launcher='"nvidia-docker"'`

My mirror list is as follows:
```
docker images
REPOSITORY                           TAG                            IMAGE ID            CREATED             SIZE
registry.docker-cn.com/nvidia/cuda   latest                         1cc6f1613121        3 weeks ago         2.24GB
nvidia/cuda                          9.0-cudnn7-devel-ubuntu16.04   afc5ab1e9a0d        3 weeks ago         2.59GB
tensorflow/tensorflow                latest                         2054925f3b43        4 weeks ago         1.34GB
nvcr.io/nvidia/tensorflow            18.07-py3                      8289b0a3b285        5 months ago        3.34GB
bvlc/caffe                           cpu                            0b577b836386        7 months ago        1.64GB
hpe/intel_caffe                      cpu                            0b577b836386        7 months ago        1.64GB
bvlc/caffe                           gpu                            ba28bcb1294c        7 months ago        3.38GB
hpe/bvlc_caffe                       cuda9-cudnn7                   ba28bcb1294c        7 months ago        3.38GB
```

error:

```
InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'fp32_vars/dense/bias/Momentum': Operation was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0 ]. Make sure the device specification refers to a valid device.
         [[Node: fp32_vars/dense/bias/Momentum = VariableV2[_class=["loc:@fp32_vars/dense/bias"], container="", dtype=DT_FLOAT, shape=[1000], shared_name="", _device="/device:GPU:0"]()]]

-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[14086,1],3]
  Exit code:    1
--------------------------------------------------------------------------
__results.end_time__= "2018-12-04:02:46:45:780"
__results.proc_pid__= 7988
__exp.model_title__="GoogleNet"
__exp.status__="failure"
__exp.status_msg__="No results have been found in this log file"
```

When I remove the argument "-Pexp.docker_launcher='"nvidia-docker"'", new error is as follows:
`python: can't open file '.py': [Errno 2] No such file or directory`

**Comment by sergey-serebryakov** [comment]
@bingws It's good you could run GPU benchmarks. We have some reference numbers [here](https://dlpg.labs.hpe.com) for various GPUs that you can use to compare performance.

I never ran TensorFlow image from NGC without GPUs. I will need to test that. I'll do it my tomorrow morning. Meanwhile, it seems that TF is compiled there against CUDA, so `nvcr.io/nvidia/tensorflow:18.07-py3 ` needs to be run with `nvidia-docker`.

**Comment by bingws** [comment]
@sergey-serebryakov Ok, look forward to your good news.

**Comment by sergey-serebryakov** [comment]
@bingws I did not have much time to investigate this issues but I think the problem is that `nvtfcnn` benchmark backend (written by NVIDIA) is tightly integrated with GPUs. I did some changes and I think it works now (I tested it with GoogleNet and AlexNet models, should work with others as well). Please, update DLBS (`git pull`), relevant commit is [this one](https://github.com/HewlettPackard/dlcookbook-dlbs/commit/c506928038fa794ceb1276c9af62abfebe48e250). BTW, when you run AlexNet, use `alexnet_owt` as model name.

So, actually now you have two options to run TensorFlow on CPUs. Option one is to use `nvtfcnn` benchmark backend (which is not very much tested on CPUs):
```bash
cd ~/projects/dlbs
source ./scripts/environment.sh
[ -d "./benchmarks/my_experiment" ] && rm -f "./benchmarks/my_experiment"
python $experimenter run -Pexp.framework='"nvtfcnn"' -Pexp.gpus='""' -Pexp.model='"alexnet_owt"'  -Pexp.replica_batch=2 -Pexp.log_file='"./benchmarks/my_experiment/tf_${exp.model}_${exp.replica_batch}.log"'
```
You do not need to provide `exp.docker_launcher` parameter anymore.

Option two is to use Google's behchmark backend `tensorflow`:
```bash
cd ~/projects/dlbs
source ./scripts/environment.sh
[ -d "./benchmarks/my_experiment" ] && rm -f "./benchmarks/my_experiment"
python $experimenter run -Pexp.framework='"tensorflow"' -Pexp.gpus='""' -Pexp.model='"googlenet"'  -Pexp.replica_batch=2 -Pexp.log_file='"./benchmarks/my_experiment/tf_${exp.model}_${exp.replica_batch}.log"' -Pexp.docker_launcher='"nvidia-docker"' -Pexp.docker_image='"nvcr.io/nvidia/tensorflow:18.07-py3"'
```
In this case you do need to provide docker launcher and also docker image because default docker image for `tensorflow` benchmark backend is different.


I suggest running both and selecting the best result. As usual, do not forget to increase number of warmup and benchmark iterations (this is super important!):
```bash
-Pexp.num_warmup_batches=100 -Pexp.num_batches=400
```

**Comment by bingws** [comment]
@sergey-serebryakov Thank you very much
